[project]
name = "cvxopt"
dynamic = ["version"]
description = "Convex optimization package"
authors = [
    {name = "M. Andersen", email = "martin.skovgaard.andersen@gmail.com"},
    {name = "J. Dahl", email = "dahl.joachim@gmail.com"},
    {name = "L. Vandenberghe", email = "vandenbe@ee.ucla.edu"}
]
requires-python = ">=3.8"
readme = {file = "README.md", content-type = "text/markdown"}
license = "GPL-3.0-or-later"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://cvxopt.org"
Source = "https://github.com/cvxopt/cvxopt"

[build-system]
requires = ["meson-python>=0.15.0", "meson>=1.1.0"]
build-backend = "mesonpy"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {package}/tests"

[tool.cibuildwheel.linux]
archs = "x86_64 aarch64"
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"
before-all = "./.ci-support/before_all_linux.sh"

[tool.cibuildwheel.linux.config-settings]
setup-args = ["-Dbuild_gsl=true", "-Dbuild_fftw=true", "-Dbuild_glpk=true", "-Dbuild_dsdp=true"]

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"
before-all = "./.ci-support/before_all_macos.sh"

[tool.cibuildwheel.macos.config-settings]
setup-args = ["-Dbuild_gsl=true", "-Dbuild_fftw=true", "-Dbuild_glpk=true", "-Dbuild_dsdp=true", "-Ddsdp_inc_dir=.local/include"]


