name: Publish source

on:
  release:
    types: [created]
    
jobs:    
  build:
    runs-on: macos-latest
    env:
      KVXOPT_BUILD_GSL: 1
      KVXOPT_BUILD_FFTW: 1
      KVXOPT_BUILD_GLPK: 1
      KVXOPT_BUILD_DSDP: 0

    strategy:
      matrix:
        python-version: [3.8]
        suite-sparse: [lib_suitesparse]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Install libraries
        run: |
            brew install openblas glpk gsl fftw suite-sparse

      - name: Build 
        run: |
          python setup.py build
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: kvxopt-source
          path: dist/*.tar.gz


      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*.tar.gz