name: Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.14']

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libopenblas-dev libsuitesparse-dev libdsdp-dev libfftw3-dev libglpk-dev libgsl-dev

    - name: Install Python build tools
      run: |
        python -m pip install --upgrade pip
        pip install meson meson-python ninja setuptools-scm build pytest pytest-cov coveralls

    - name: Build wheel
      run: |
        python -m build --wheel \
          -C setup-args="-Dbuild_gsl=true" \
          -C setup-args="-Dbuild_fftw=true" \
          -C setup-args="-Dbuild_glpk=true" \
          -C setup-args="-Dbuild_dsdp=true" \
          -C setup-args="-Ddsdp_inc_dir=/usr/include/dsdp"

    - name: Install wheel
      run: pip install --no-index --find-links=${{ github.workspace }}/dist cvxopt

    - name: Test with pytest
      run: |
        python -c "from cvxopt import blas,lapack,amd,cholmod,umfpack,glpk,dsdp,gsl,fftw"
        pytest --cov=cvxopt tests
