name: macOS build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      DSDP_VERSION: 5.8
      DSDP_SHA256: 26aa624525a636de272c0b329e2dfd01a0d5b7827f1c1c76f393d71e37dead70

    strategy:
      matrix:
        python-version: ['3.14']

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Homebrew dependencies
      run: |
        brew install suite-sparse openblas fftw gsl glpk
        echo "PKG_CONFIG_PATH=$(brew --prefix openblas)/lib/pkgconfig:$(brew --prefix)/lib/pkgconfig" >> $GITHUB_ENV

    - name: Install Python build tools
      run: |
        python -m pip install --upgrade pip
        pip install meson meson-python ninja setuptools-scm build pytest pytest-cov coveralls

    - name: Build DSDP
      run: |
        wget http://www.mcs.anl.gov/hs/software/DSDP/DSDP${DSDP_VERSION}.tar.gz
        echo "${DSDP_SHA256}  DSDP${DSDP_VERSION}.tar.gz" > DSDP.sha256
        shasum -a 256 -c DSDP.sha256
        tar -xf DSDP${DSDP_VERSION}.tar.gz
        mkdir -p .local/lib .local/include
        cd DSDP${DSDP_VERSION}
        patch -p1 < ${{ github.workspace }}/.github/workflows/dsdp.patch
        make PREFIX=${{ github.workspace }}/.local \
          LAPACKBLAS="$(pkg-config --libs openblas)" \
          IS_OSX=1 DSDPROOT=$(pwd) install

    - name: Build wheel
      run: |
        python -m build --wheel \
          -C setup-args="-Dbuild_gsl=true" \
          -C setup-args="-Dbuild_fftw=true" \
          -C setup-args="-Dbuild_glpk=true" \
          -C setup-args="-Dbuild_dsdp=true" \
          -C setup-args="-Ddsdp_inc_dir=${{ github.workspace }}/.local/include" \
          -C setup-args="-Ddsdp_lib_dir=${{ github.workspace }}/.local/lib"

    - name: Install wheel
      run: pip install --no-index --find-links=${{ github.workspace }}/dist cvxopt

    - name: Test with pytest
      run: |
        python -c "from cvxopt import blas,lapack,amd,cholmod,umfpack,glpk,gsl,fftw"
        pytest --cov=cvxopt tests
