name: Bump version and publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.56
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      # write some files into a dist folder
      - name: Write
        run: |
          mkdir -p dist
          echo "Tag: ${{ needs.tagging.output.new_tag }}" 
          touch dist/maffay.txt

      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tagging.output.new_tag }}
          generate_release_notes: true
          files: dist/*

