name: Bump version and publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.56
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      # write some files into a dist folder
      - name: Write
        run: |
          mkdir -p dist
          echo "Tag: ${{ needs.tagging.outputs.new_tag }}" 
          echo "Tag: ${{ needs.tagging.outputs.new_tag }}" > dist/maffay.txt
          ls -R dist
          # todo: build wheels etc.

      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tagging.outputs.new_tag }}
          generate_release_notes: true
          files: dist/*

  # this will be publication to PyPI
  #publish:
  #  needs: tag
  #  runs-on: ubuntu-latest
  #  environment: release

  #  permissions:
  #    contents: read
  #    # This permission is required for trusted publishing.
  #    id-token: write

  #  steps:
  #    - name: Checkout [${{ github.repository }}]
  #      uses: actions/checkout@v4

  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: dist
  #        path: dist
