name: Windows build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        python-version: ['3.14']

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        activate-environment: build-env

    - name: Install dependencies
      run: |
        conda install -y openblas "suitesparse>=7" pkg-config \
          meson meson-python ninja pytest pytest-cov
        pip install build coveralls

    - name: Build wheel
      run: |
        export PKG_CONFIG_PATH="$CONDA_PREFIX/Library/lib/pkgconfig:$CONDA_PREFIX/Library/share/pkgconfig"
        python -m build --wheel \
          -C setup-args="-Dsuitesparse_lib_dir=$(cygpath -m "$CONDA_PREFIX/Library/lib")" \
          -C setup-args="-Dsuitesparse_inc_dir=$(cygpath -m "$CONDA_PREFIX/Library/include/suitesparse")"

    - name: Install wheel
      run: pip install --no-index --find-links=dist cvxopt

    - name: Test
      run: |
        python -c "from cvxopt import blas,lapack,amd,cholmod,umfpack"
        pytest tests
